env:
  contexts:
    - name: target
      urls:
        - ${ZAP_TARGET}
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
jobs:
  - type: passiveScan-config
    parameters:
      maxAlertsPerRule: 10
  - type: spider
    parameters:
      context: target
      maxDuration: 1
  - type: passiveScan-wait
    parameters:
      maxDuration: 2
  - type: activeScan
    parameters:
      context: target
      maxScanDurationInMins: 5
      maxRuleDurationInMins: 1
  - type: report
    parameters:
      template: traditional-html
      reportDir: ${ZAP_REPORT_DIR}
      reportFile: report.html
  - type: report
    parameters:
      template: traditional-json
      reportDir: ${ZAP_REPORT_DIR}
      reportFile: report.json
  - type: exitStatus
    parameters:
      errorLevel: High
      warnLevel: ${ZAP_WARN_LEVEL}
